apiVersion: v1
kind: ConfigMap
metadata:
  name: init-users
  labels:
    app: init-users
    chart: init-users-chart
    release: {{ .Release.Name }}
data:
  init-users.sh: |
    #! /bin/bash
    groupadd supergroup
    useradd -m -g supergroup -s /bin/bash hdfs
    useradd -m -g supergroup -s /bin/bash hive
    useradd -m -g supergroup -s /bin/bash spark
    useradd -m -g supergroup -s /bin/bash ranger-admin
    useradd -m -g supergroup -s /bin/bash ranger-kms
    useradd -m -g supergroup -s /bin/bash hue
    useradd -m -g supergroup -s /bin/bash admin
    