apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-batch
  labels:
    app: secrets-batch
    chart: secrets-batch-chart
    release: {{ .Release.Name }}
data:
  script: |
    #! /bin/bash
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "addprinc -randkey hdfs@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "addprinc -randkey hive@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "addprinc -randkey spark@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "addprinc -randkey HTTP@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "ktadd -norandkey -k /tmp/hdfs.keytab hdfs@" .Values.global.kerberosRealm " HTTP@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "ktadd -norandkey -k /tmp/hive.keytab hive@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "ktadd -norandkey -k /tmp/spark.keytab spark@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} cp {{ template "hdfs-k8s.krb5.fullname" . }}:/tmp/hdfs.keytab /tmp/hdfs.keytab
    kubectl -n {{ .Release.Namespace }} cp {{ template "hdfs-k8s.krb5.fullname" . }}:/tmp/hive.keytab /tmp/hive.keytab
    kubectl -n {{ .Release.Namespace }} cp {{ template "hdfs-k8s.krb5.fullname" . }}:/tmp/spark.keytab /tmp/spark.keytab
    kubectl -n {{ .Release.Namespace }} create secret generic platform-labp7-hdfs-krb5-keytabs
    