apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-batch
  labels:
    app: secrets-batch
    chart: secrets-batch-chart
    release: {{ .Release.Name }}
data:
  secrets-batch.sh: |
    #! /bin/bash
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ addprinc -randkey template "hdfs-principal" . | quote }} 
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q "addprinc -randkey " {{ template "hive-principal" . }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q "addprinc -randkey " {{ template "spark-principal" . }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q "addprinc -randkey " {{ template "http-principal" . }}