apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-batch
  labels:
    app: secrets-batch
    chart: secrets-batch-chart
    release: {{ .Release.Name }}
data:
  secrets-batch.sh: |
    #! /bin/bash
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "addprinc -randkey hdfs@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "addprinc -randkey hive@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "addprinc -randkey spark@" .Values.global.kerberosRealm | quote }}
    kubectl -n {{ .Release.Namespace }} exec {{ template "hdfs-k8s.krb5.fullname" . }} -- kadmin.local -q {{ print "addprinc -randkey HTTP@" .Values.global.kerberosRealm | quote }}