# A headless service to create DNS records.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore
  labels:
    app: hive
    chart: hive-k8s
    release: hive-metastore-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive
      release: hive-metastore-k8s
#  serviceName: hive-metastore-service
  template:
    metadata:
      labels:
        app: hive
        release: hive-metastore-k8s     
    spec:
      containers:
        - name: hive-metastore-server
          image: bringg/hive:3.1.2
          env:
          command: ['/bin/sh']
          args: ["-c","hive --service metastore"]
          ports:
          - containerPort: 9083
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf/
              readOnly: true  
            - name: kerberos-config
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
              readOnly: true
            - name: kerberos-keytabs
              mountPath: /etc/security/
              readOnly: true  
      restartPolicy: Always
      volumes:
        - name: kerberos-config
          configMap:
            name: kerberos-config-map
        - name: hive-config
          configMap:
            name: hive-config-map    
        - name: kerberos-keytabs
          secret:
            secretName: kerberos-keytabs-secret
