apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-labp7.fullname" . }}
  labels:
    {{- include "platform-labp7.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30524 
  selector:
    {{- include "platform-labp7.selectorLabels" . | nindent 4 }}
