FROM adoptopenjdk/openjdk8
RUN apt update -y && apt install python3 nano -y && apt install wget nano -y 
RUN mkdir /usr/share/java/
RUN wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar -O /usr/share/java/postgresql.jar
COPY ranger-2.3.0-kms.tar.gz /opt/
RUN tar xzvf /opt/ranger-2.3.0-kms.tar.gz -C /opt/
WORKDIR /opt/ranger-2.3.0-kms
ENTRYPOINT [ "/bin/bash" ] 
