apiVersion: v1
kind: ConfigMap
metadata:
  name: init-ranger-hdfs
  labels:
    app: init-ranger-hdfs
    chart: init-ranger-hdfs-chart
    release: {{ .Release.Name }}
data:
  init-ranger.sh: |
    #! /bin/bash
    groupadd hadoop
    adduser hadoop -g hadoop
    ln -s /opt/hadoop-3.1.1/etc /opt/hadoop-3.1.1/hadoop/etc
    mv -f /conf/install.properties /opt/hadoop-3.1.1/ranger-2.3.0-hdfs-plugin
    /opt/hadoop-3.1.1/ranger-2.3.0-hdfs-plugin/enable-hdfs-plugin.sh