apiVersion: v1
kind: ConfigMap
metadata:
  name: init-ranger-hdfs
  labels:
    app: init-ranger-hdfs
    chart: init-ranger-hdfs-chart
    release: {{ .Release.Name }}
data:
  init-ranger.sh: |
    #! /bin/bash
    groupadd hadoop
    useradd -g hadoop hadoop
    mkdir /opt/hadoop-3.1.1/hadoop
    ln -s /opt/hadoop-3.1.1/etc /opt/hadoop-3.1.1/hadoop/etc
    cat  /conf/install.properties > /opt/hadoop-3.1.1/ranger-2.3.0-hdfs-plugin/install.properties
    rm -f /opt/hadoop-3.1.1/etc/hadoop/core-site.xml /opt/hadoop-3.1.1/etc/hadoop/hdfs-site.xml
    cp -f /etc/hadoop-custom-conf/core-site.xml /etc/hadoop-custom-conf/hdfs-site.xml /opt/hadoop-3.1.1/etc/hadoop/
    /opt/hadoop-3.1.1/ranger-2.3.0-hdfs-plugin/enable-hdfs-plugin.sh