apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ranger-admin.config.kms.site" . }}
  labels:
    app: {{ template "ranger-admin.app.name" . }}
    chart: {{ template "ranger-admin.subchart" . }}
    release: {{ .Release.Name }}
data:
  ranger-kms-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>ranger.authentication.method</name>
        <value>LDAP,KERBEROS</value>
      </property>
      <property>
        <name>ranger.kms.authentication.type</name>
        <value>kerberos</value>
      </property>
      <property>
        <name>ranger.kms.keytab</name>
        <value>/etc/security/ranger-kms.keytab</value>
      </property>
      <property>
        <name>ranger.kms.principal</name>
        <value>ranger-kms/_HOST@LABP7.CNAM</value>
      </property>
      <property>
        <name>ranger.service.http.enabled</name>
        <value>true</value>
      </property>
      <property>
        <name>ranger.service.http.port</name>
        <value>9292</value>
      </property>
      <property>
        <name>ranger.service.http.authentication.enabled</name>
        <value>true</value>
      </property>
      <property>
        <name>ranger.service.http.audit.log4j.appender.file</name>
        <value>/var/log/ranger/kms/kms.log</value>
      </property>
    </configuration>
