apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ranger-admin.config.spark.audit" . }}
  labels:
    app: {{ template "ranger-admin.app.name" . }}
    chart: {{ template "ranger-admin.subchart" . }}
    release: {{ .Release.Name }}
data:
  kms-site.xml: |
    <configuration>

      <property>
          <name>xasecure.audit.is.enabled</name>
          <value>true</value>
      </property>

      <property>
          <name>xasecure.audit.destination.db</name>
          <value>false</value>
      </property>

      <property>
          <name>xasecure.audit.destination.db.jdbc.driver</name>
          <value>com.mysql.jdbc.Driver</value>
      </property>

      <property>
          <name>xasecure.audit.destination.db.jdbc.url</name>
          <value>jdbc:postgresql://{{ include "postgresql.primary.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ include "postgresql.service.port" . }}/ranger_audit</value>
      </property>

      <property>
          <name>xasecure.audit.destination.db.password</name>
          <value>${env:POSTGRES_PASSWORD}</value>
      </property>

      <property>
          <name>xasecure.audit.destination.db.user</name>
          <value>postgres</value>
      </property>

  </configuration>