apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark.config.fullname" . }}
  labels:
    app: {{ template "spark.app.name" . }}
    chart: {{ template "spark.subchart" . }}
    release: {{ .Release.Name }}
data:
  spark-defaults.conf: |
    spark.kubernetes.driver.master k8s://{{ .Values.global.kubernetes.master.host }}:{{ .Values.global.kubernetes.master.port }}
    spark.kubernetes.authenticate.serviceAccountName default
    spark.kubernetes.namespace {{ .Release.Namespace }}
    spark.kubernetes.container.image 55.39.206.23:5000/spark-3.2.2:postgresql_kyuubi
    spark.sql.warehouse.dir hdfs://{{ template "namenode-svc-0" . }}:8020/hive/warehouse
    spark.executor.memory 1g
    spark.executor.cores 1
    spark.executor.instances 3
    spark.driver.host {{ template "spark.spark-svc-0" . }}
    spark.driver.port 16780
    {{- if .Values.global.ranger.enabled }}
    spark.sql.extensions org.apache.kyuubi.plugin.spark.authz.ranger.RangerSparkExtension
    {{- end }}
    spark.kerberos.principal spark/{{ template "spark.spark-svc-0" . }}@{{ .Values.global.kerberosRealm }}
    spark.kerberos.keytab /etc/security/spark.keytab
    spark.kubernetes.kerberos.krb5.path /etc/krb5.conf
    spark.sql.adaptive.enabled true
    spark.sql.adaptive.coalescepartitions.enable true
    spark.sql.adaptive.skewjoin.enabled true
    spark.dynamicallocation.enabled true
    spark.dynamicallocation.maxexecutors 20


