apiVersion: v1
kind: ConfigMap
metadata:
  name: hue-config
data:
  hue-ini: |
    [desktop]
    secret_key=hue123
    app_blacklist=filebrowser,search,hbase,security,jobbrowser,oozie
    django_debug_mode=false
    gunicorn_work_class=sync
    enable_prometheus=true
    enable_connectors=true
    enable_hue_5=true

    [[kerberos]]
    # Path to Hue's Kerberos keytab file
    hue_keytab=/etc/security/hue.keytab
    # Kerberos principal name for Hue
    hue_principal=hue/{{ template "hue.hue-svc-0" . }}@{{ .Values.global.kerberosRealm }}
    # add kinit path for non root users
    kinit_path=/usr/bin/kinit

    [beeswax]
    # Host where HiveServer2 is running.
    # If Kerberos security is enabled, use fully-qualified domain name (FQDN).
    hive_server_host={{ template "spark-svc-0" . }}
    # Port where HiveServer2 Thrift server runs on.
    hive_server_port=10000

    [hadoop]
    [[hdfs_clusters]]
    [[[default]]]
    # Enter the host and port on which you are running the Hadoop NameNode
    namenode_host={{ template "namenode-svc-0" . }}
    hdfs_port=8020
    http_port=9870
    security_enabled=true

    [notebook]
    [[interpreters]]
    {{ .Values.hue.interpreters | indent 4 }}
