apiVersion: v1
kind: Service
metadata:
  name: {{ include "hue.fullname" . }}
  labels:
    {{- include "hue.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hue.selectorLabels" . | nindent 4 }}
  ports:
  - name: hue
    port: 8888
  type: NodePort
