FROM egdsandaru/apache-ranger-admin:1.0.0
RUN apt update -y
RUN apt install python3 nano -y
RUN mkdir /usr/share/java/
RUN wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar -O /usr/share/java/postgresql.jar
RUN rm -rf /opt/ranger-2.1.0-admin/*
COPY ranger-2.3.0-admin.tar.gz /opt/ranger-2.1.0-admin/
RUN tar xzvf /opt/ranger-2.1.0-admin/ranger-2.3.0-admin.tar.gz -C /opt/ranger-2.1.0-admin/ 
RUN mv /opt/ranger-2.1.0-admin/ranger-2.3.0-admin/* /opt/ranger-2.1.0-admin/
RUN rm -rf /opt/ranger-2.1.0-admin/ranger-2.3.0-admin/ /opt/ranger-2.1.0-admin/ranger-2.3.0-admin.tar.gz /opt/ranger-2.1.0-admin.tar.gz
WORKDIR "/opt/ranger-2.1.0-admin/"