apiVersion: v1
kind: ConfigMap
metadata:
  name: init-ranger-admin
  labels:
    app: init-ranger-admin
    chart: init-ranger-admin-chart
    release: {{ .Release.Name }}
data:
  init-ranger-admin.sh: |
    #! /bin/bash

    users="hdfs spark hive ranger-admin ranger-kms"

    status_code=$(curl -s -o /dev/null -w "%{http_code}" -X  'GET' "http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/plugins/policies/service/name/ranger-admin" -H 'accept: application/json')

    if [[ "$status_code" -eq 200 ]] ; then
      exit 0
    else
      curl -X 'POST' \
      "http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/public/v2/api/service" \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '  {
        "id": 1,
        "guid": "1bd6df43-ce74-47db-9c25-a8101a4826f9",
        "isEnabled": true,
        "createdBy": "Admin",
        "updatedBy": "Admin",
        "createTime": 1682598079926,
        "updateTime": 1682598079929,
        "version": 1,
        "type": "hive",
        "name": "ranger-admin",
        "displayName": "ranger-admin",
        "description": "",
        "configs": {
          "password": "ranger-admin",
          "ranger.plugin.audit.filters": "[{'\''accessResult'\'':'\''DENIED'\'','\''isAudited'\'':true},{'\''actions'\'':['\''METADATA OPERATION'\''],'\''isAudited'\'':false},{'\''users'\'':['\''hive'\'','\''hue'\''],'\''actions'\'':['\''SHOW_ROLES'\''],'\''isAudited'\'':false}]",
          "jdbc.driverClassName": "org.apache.hive.jdbc.HiveDriver",
          "jdbc.url": "jdbc:hive2://{{ .Values.global.kubernetes.master.host }}:30527/default;principal=hive/{{ include "spark.spark-svc-0" . }}@LABP7.CNAM",
          "username": "admin"
        },
        "policyVersion": 9,
        "policyUpdateTime": 1682598081340,
        "tagVersion": 1,
        "tagUpdateTime": 1682598079935
      }
    '
    curl -X 'POST' \
      "http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/public/v2/api/service" \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '  {
              "id":2,
              "guid":"262a649a-405a-4027-8e6b-84f4c03228aa",
              "isEnabled":true,
              "createdBy":"Admin",
              "updatedBy":"Admin",
              "createTime":1683273519056,
              "updateTime":1683273519058,
              "version":1,
              "type":"hdfs",
              "name":"ranger-admin-hdfs",
              "displayName":"ranger-admin-hdfs",
              "description":"",
              "configs":{
                  "username":"hdfs",
                  "password":"hdfs",
                  "fs.default.name":"hdfs://{{ template "namenode-svc-0" . }}:8020",
                  "hadoop.security.authorization":false,
                  "hadoop.security.authentication":"kerberos",
                  "hadoop.security.auth_to_local":"",
                  "dfs.datanode.kerberos.principal":"hdfs/{{ template "namenode-svc-0" . }}@LABP7.CNAM",
                  "dfs.namenode.kerberos.principal":"hdfs/{{ template "namenode-svc-0" . }}@LABP7.CNAM",
                  "dfs.secondary.namenode.kerberos.principal":"",
                  "hadoop.rpc.protection":"privacy",
                  "commonNameForCertificate":"",
                  "ranger.plugin.audit.filters":"[]"
              },
              "policyVersion":9,
              "policyUpdateTime":1683278824637,
              "tagVersion":1,
              "tagUpdateTime":1683273519070,
              "tagService":""
            }
    '

      for str in $users; do

        curl "http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/xusers/secure/users/$str?forceDelete=true" \
        -X 'DELETE' \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
        -H 'Connection: keep-alive' \
        -H 'Content-Type: application/json' \
        --compressed \
        --insecure

        curl "http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/xusers/secure/users" \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
        -H 'Connection: keep-alive' \
        -H 'Content-Type: application/json' \
        --data "{\"name\":\"$str\",\"password\":\"Admin-$str-123\",\"firstName\":\"$str\",\"lastName\":\"$str\",\"userRoleList\":[\"ROLE_SYS_ADMIN\"],\"groupIdList\":null,\"status\":1}" \
        --compressed \
        --insecure

      done
    fi