apiVersion: v1
kind: Service
metadata:
  name: {{ include "ranger-admin.fullname" . }}
  labels:
    {{- include "ranger-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ranger-admin.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ranger-admin.fullname" . }}-node-port
  labels:
    {{- include "ranger-admin.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30523
  selector:
    {{- include "ranger-admin.selectorLabels" . | nindent 4 }}