apiVersion: v2
name: platform-labp7
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
dependencies:
  - name: platform-config
    version: "0.1.0"
    repository: "file://../platform-config"
    condition: condition.subchart.config
    tags:
      - ranger
      - simple
      - ranger
  - name: spark
    version: "0.1.0"
    repository: "file://../platform-spark"
    condition: condition.subchart.spark
    tags:
      - ranger
      - simple
  - name: hive-meta-store
    version: "0.1.0"
    repository: "file://../platform-hive-metastore"
    condition: condition.subchart.hive-meta-store
    tags:
      - external
  - name: ranger-kms
    version: "0.1.0"
    repository: "file://../platform-ranger-kms"
    condition: condition.subchart.ranger-kms
    tags:
      - ranger
  - name: ranger-admin
    version: "0.1.0"
    repository: "file://../platform-ranger-admin"
    condition: condition.subchart.ranger-admin
    tags:
      - ranger
  - name: zookeeper
    version: "2.1.6"
    repository: https://charts.helm.sh/incubator
    condition: condition.subchart.zookeeper
    tags:
      - ha
      - kerberos
  - name: hdfs-config-k8s
    version: "0.1.0"
    repository: "file://../hdfs-config-k8s"
    condition: condition.subchart.config
    tags:
      - ha
      - kerberos
      - simple
      - ranger
  - name: hdfs-krb5-k8s
    version: "0.1.0"
    repository: "file://../hdfs-krb5-k8s"
    condition: condition.subchart.kerberos
    tags:
      - kerberos
      - simple
      - ranger
  - name: hdfs-journalnode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-journalnode-k8s"
    condition: condition.subchart.journalnode
    tags:
      - ha
      - kerberos
  - name: hdfs-namenode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-namenode-k8s"
    condition: condition.subchart.namenode
    tags:
      - ha
      - kerberos
  # Non-HA namenode. Disabled by default
  - name: hdfs-simple-namenode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-simple-namenode-k8s"
    condition: condition.subchart.simple-namenode
    tags:
      - simple
      - ranger
  - name: hdfs-datanode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-datanode-k8s"
    condition: condition.subchart.datanode
    tags:
      - ha
      - kerberos
      - simple
      - ranger
  - name: hdfs-client-k8s
    version: "0.1.0"
    repository: "file://../hdfs-client-k8s"
    condition: condition.subchart.client
    tags:
      - ha
      - kerberos
      - simple
      - ranger
  - name: common
    version: 2.x.x
    repository: "file://../platform-common"
    tags:
      - ha
      - kerberos
      - simple
      - ranger
  - name: postgresql
    version: 12.2.3
    repository: "file://../platform-postgresql"
    tags:
      - ha
      - kerberos
      - simple
      - ranger
  - name: hue
    version: 1.0.3
    repository: "file://../platform-hue"
    tags:
      - ha
      - kerberos
      - simple
      - ranger
  - name: httpfs
    version: 0.20.2
    repository: "file://../platform-httpfs"
    tags:
      - ha
      - kerberos
      - simple
      - ranger