dependencies:
  - name: platform-config
    version: "0.1.0"
    repository: "file://../platform-config"
    condition: condition.subchart.config
    tags:
      - ranger
      - simple
  - name: spark
    version: "0.1.0"
    repository: "file://../platform-spark"
    condition: condition.subchart.spark
    tags:
      - ranger
      - simple
  - name: hive-meta-store
    version: "0.1.0"
    repository: "file://../platform-hive-metastore"
    condition: condition.subchart.hive-meta-store
    tags:
      - ranger
      - simple
  - name: ranger-kms
    version: "0.1.0"
    repository: "file://../platform-ranger-kms"
    condition: condition.subchart.ranger-kms
    tags:
      - ranger
  - name: ranger-policy
    version: "0.1.0"
    repository: "file://../platform-ranger-policy"
    condition: condition.subchart.ranger-policy
    tags:
      - ranger
  - name: zookeeper
    version: "2.1.6"
    repository: https://charts.helm.sh/incubator
    condition: condition.subchart.zookeeper
    tags:
      - ha
      - kerberos
  - name: hdfs-config-k8s
    version: "0.1.0"
    repository: "file://../hdfs-config-k8s"
    condition: condition.subchart.config
    tags:
      - ha
      - kerberos
      - simple
  - name: hdfs-krb5-k8s
    version: "0.1.0"
    repository: "file://../hdfs-krb5-k8s"
    condition: condition.subchart.kerberos
    tags:
      - kerberos
  - name: hdfs-journalnode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-journalnode-k8s"
    condition: condition.subchart.journalnode
    tags:
      - ha
      - kerberos
  - name: hdfs-namenode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-namenode-k8s"
    condition: condition.subchart.namenode
    tags:
      - ha
      - kerberos
  # Non-HA namenode. Disabled by default
  - name: hdfs-simple-namenode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-simple-namenode-k8s"
    condition: condition.subchart.simple-namenode
    tags:
      - simple
  - name: hdfs-datanode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-datanode-k8s"
    condition: condition.subchart.datanode
    tags:
      - ha
      - kerberos
      - simple
  - name: hdfs-client-k8s
    version: "0.1.0"
    repository: "file://../hdfs-client-k8s"
    condition: condition.subchart.client
    tags:
      - ha
      - kerberos
      - simple
