dependencies:
  - name: platform-config
    version: "0.1.0"
    repository: "file://../platform-config"
    condition: condition.subchart.config
    tags:
      - ranger
      - simple
  - name: hdfs
    version: "0.1.0"
    repository: "file://../platform-hdfs/charts/hdfs-k8s"
    condition: condition.subchart.hdfs
    tags:
      - ranger
      - simple
  - name: spark
    version: "0.1.0"
    repository: "file://../platform-spark"
    condition: condition.subchart.spark
    tags:
      - ranger
      - simple
  - name: hive-meta-store
    version: "0.1.0"
    repository: "file://../platform-hive-metastore"
    condition: condition.subchart.hive-meta-store
    tags:
      - ranger
      - simple

  - name: ranger-kms
    version: "0.1.0"
    repository: "file://../platform-ranger-kms"
    condition: condition.subchart.ranger-kms
    tags:
      - ranger
  - name: ranger-policy
    version: "0.1.0"
    repository: "file://../platform-ranger-policy"
    condition: condition.subchart.ranger-policy
    tags:
      - ranger
