image:
   registry: "gethue"
   tag: "latest"
   pullPolicy: "Always"
hue:
  replicas: 1
  database:
    create: false
    persist: false
    engine: "postgresql_psycopg2"
    host: "postgres-hue"
    port: 5432
    user: "postgres"
    password: "E6WQgFr6Ub"
    #password_script: echo ${POSTGRES_PASSWORD}
    name: "hue"
    storageName: "microk8s-hostpath"
  interpreters: |
    [[[hive]]]
    # The name of the snippet.
    name=Hive
    # The backend connection to use to communicate with the server.
    interface=hiveserver2
  ini: "" 
balancer:
  enabled: true
api:
  enabled: false
  domain: api.gethue.com
workers:
  enabled: false
  replicas: 1
scheduler:
  enabled: false
websocket:
  enabled: false
  replicas: 1
monitoring:
  enabled: false
alerting:
  enabled: false
tracing:
  enabled: false
cron:
  enabled: false
  emailStats: "0 13 * * WED,SUN"
ingress:
  create: false
  hasAuth: false
  type: "nginx"
  # type: "nginx-ssl"
  # type: "nginx-ssl-staging"
  # type: "traefik"
  domain: "demo.gethue.com"
  # extraHosts:
  # - "demo.hue.com"
  # annotations: {}
  email: "team@gethue.com"
  loadBalancerIp: "127.0.0.1"
aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: "us-east-1"
hive:
  site: |
    <!---->
architecture: standalone

## Pod Annotations
# podAnnotations: {}

## Pod Labels
# podLabels: {}
