FROM adel1992/namenode:3.1.1
COPY ./ranger-2.3.0-hdfs-plugin.tar.gz /opt/hadoop-3.1.1/
RUN tar xzvf /opt/hadoop-3.1.1/ranger-2.3.0-hdfs-plugin.tar.gz -C /opt/hadoop-3.1.1/
RUN rm -f /opt/hadoop-3.1.1/ranger-2.3.0-hdfs-plugin.tar.gz