apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-meta-store.fullname" . }}
  labels:
    {{- include "hive-meta-store.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: thrift
  selector:
    {{- include "hive-meta-store.selectorLabels" . | nindent 4 }}
