apiVersion: v1
kind: ConfigMap
metadata:
  name: init-ranger-admin
  labels:
    app: init-ranger-admin
    chart: init-ranger-admin-chart
    release: {{ .Release.Name }}
data:
  init-ranger-admin.sh: |
    #! /bin/bash

    master={{ .Values.global.kubernetes.master.host | quote }}
    users="hdfs spark hive ranger-admin ranger-kms"

    status_code=$(curl -X 'GET' "http://admin:admin@$master:30523/service/plugins/policies/service/name/ranger-admin" -H 'accept: application/json')

    if [[ "$status_code" -eq 200 ]] ; then
      exit 0
    else
      curl -X 'POST' \
      "http://admin:admin@$master:30523/service/public/v2/api/service" \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '  {
        "id": 1,
        "guid": "1bd6df43-ce74-47db-9c25-a8101a4826f9",
        "isEnabled": true,
        "createdBy": "Admin",
        "updatedBy": "Admin",
        "createTime": 1682598079926,
        "updateTime": 1682598079929,
        "version": 1,
        "type": "hive",
        "name": "ranger-admin",
        "displayName": "ranger-admin",
        "description": "",
        "configs": {
          "password": "admin",
          "ranger.plugin.audit.filters": "[{'\''accessResult'\'':'\''DENIED'\'','\''isAudited'\'':true},{'\''actions'\'':['\''METADATA OPERATION'\''],'\''isAudited'\'':false},{'\''users'\'':['\''hive'\'','\''hue'\''],'\''actions'\'':['\''SHOW_ROLES'\''],'\''isAudited'\'':false}]",
          "jdbc.driverClassName": "org.apache.hive.jdbc.HiveDriver",
          "jdbc.url": "jdbc:hive2://$master:30527/default;principal=hive/{{ include "spark.spark-svc-0" . }}@LABP7.CNAM",
          "username": "admin"
        },
        "policyVersion": 9,
        "policyUpdateTime": 1682598081340,
        "tagVersion": 1,
        "tagUpdateTime": 1682598079935
      }
    '

      for str in $users; do

        curl "http://admin:admin@$master:30523/service/xusers/secure/users/$str?forceDelete=true" \
        -X 'DELETE' \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
        -H 'Connection: keep-alive' \
        -H 'Content-Type: application/json' \
        --compressed \
        --insecure

        curl "http://admin:admin@$master:30523/service/xusers/secure/users" \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
        -H 'Connection: keep-alive' \
        -H 'Content-Type: application/json' \
        --data "{\"name\":\"$str\",\"password\":\"Admin-$str-123\",\"firstName\":\"$str\",\"lastName\":\"$str\",\"userRoleList\":[\"ROLE_SYS_ADMIN\"],\"groupIdList\":null,\"status\":1}" \        --compressed \
        --insecure

      done
    fi