apiVersion: v1
kind: ConfigMap
metadata:
  name: init-ranger-admin
  labels:
    app: init-ranger-admin
    chart: init-ranger-admin-chart
    release: {{ .Release.Name }}
data:
  init-ranger-admin.sh: |
    #! /bin/bash
    curl -X 'POST' \
      'http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/public/v2/api/service' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -H 'X-XSRF-HEADER: kceqhSS0KfLGgxVJEz3l' \
      -d '  {
        "id": 1,
        "guid": "1bd6df43-ce74-47db-9c25-a8101a4826f9",
        "isEnabled": true,
        "createdBy": "Admin",
        "updatedBy": "Admin",
        "createTime": 1682598079926,
        "updateTime": 1682598079929,
        "version": 1,
        "type": "hive",
        "name": "ranger-admin",
        "displayName": "ranger-admin",
        "description": "",
        "configs": {
          "password": "admin",
          "ranger.plugin.audit.filters": "[{'\''accessResult'\'':'\''DENIED'\'','\''isAudited'\'':true},{'\''actions'\'':['\''METADATA OPERATION'\''],'\''isAudited'\'':false},{'\''users'\'':['\''hive'\'','\''hue'\''],'\''actions'\'':['\''SHOW_ROLES'\''],'\''isAudited'\'':false}]",
          "jdbc.driverClassName": "org.apache.hive.jdbc.HiveDriver",
          "jdbc.url": "jdbc:hive2://{{ .Values.global.kubernetes.master.host }}:30527/default;principal=hive/{{ include "spark.spark-svc-0" . }}@LABP7.CNAM",
          "username": "admin"
        },
        "policyVersion": 9,
        "policyUpdateTime": 1682598081340,
        "tagVersion": 1,
        "tagUpdateTime": 1682598079935
      }
    '
      curl 'http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/xusers/secure/users' \
      -H 'Accept: application/json, text/javascript, */*; q=0.01' \
      -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
      -H 'Connection: keep-alive' \
      -H 'Content-Type: application/json' \
      --data '{"name":"hdfs","password":"Hdfs-123","firstName":"hdfs","lastName":"hdfs","emailAddress":"adel.mejri@talan.com"$
      --compressed \
      --insecure
      curl 'http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/xusers/secure/users' \
      -H 'Accept: application/json, text/javascript, */*; q=0.01' \
      -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
      -H 'Connection: keep-alive' \
      -H 'Content-Type: application/json' \
      --data '{"name":"spark","password":"Spark-123","firstName":"spark","lastName":"spark","emailAddress":"adel.mejri@talan.com"$
      --compressed \
      --insecure
      curl 'http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/xusers/secure/users' \
      -H 'Accept: application/json, text/javascript, */*; q=0.01' \
      -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
      -H 'Connection: keep-alive' \
      -H 'Content-Type: application/json' \
      --data '{"name":"ranger-admin","password":"Ranger-admin-123","firstName":"ranger-admin","lastName":"ranger-admin","emailAddress":"adel.mejri@talan.com"$
      --compressed \
      --insecure
      curl 'http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/xusers/secure/users' \
      -H 'Accept: application/json, text/javascript, */*; q=0.01' \
      -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
      -H 'Connection: keep-alive' \
      -H 'Content-Type: application/json' \
      --data '{"name":"ranger-kms","password":"Ranger-kms-123","firstName":"ranger-kms","lastName":"ranger-admin","emailAddress":"adel.mejri@talan.com"$
      --compressed \
      --insecure
      curl 'http://admin:admin@{{ .Values.global.kubernetes.master.host }}:30523/service/xusers/secure/users' \
      -H 'Accept: application/json, text/javascript, */*; q=0.01' \
      -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
      -H 'Connection: keep-alive' \
      -H 'Content-Type: application/json' \
      --data '{"name":"hive","password":"Hive-123","firstName":"hive","lastName":"hive","emailAddress":"adel.mejri@talan.com"$
      --compressed \
      --insecure