apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}
  labels:
    {{- include "spark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: thrift
  clusterIP: None
  selector:
    {{- include "spark.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-node-port
  labels:
    {{- include "spark.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 10000
      protocol: TCP
      name: thrift
      nodePort: 30527
    - port: 4040
      protocol: TCP
      name: http
      nodePort: 30526
  selector:
    {{- include "spark.selectorLabels" . | nindent 4 }}