apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}
  labels:
    {{- include "spark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: thrift
  selector:
    {{- include "spark.selectorLabels" . | nindent 4 }}
