apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hdfs-k8s.krb5.fullname" . }}
  labels:
    app: {{ template "hdfs-k8s.krb5.name" . }}
    chart: {{ template "hdfs-k8s.subchart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  service.keyfile: dWlkPWFkbWluLG91PXN5c3RlbSN7SEVYfTczNjU2MzcyNjU3NA==