apiVersion: v1
kind: Service
metadata:
  name: {{ template "hdfs-k8s.krb5.fullname" . }}
  labels:
    app: {{ template "hdfs-k8s.krb5.name" . }}
    chart: {{ template "hdfs-k8s.subchart" . }}
    release: {{ .Release.Name }}
  annotations:
    # TODO: Deprecated. Replace tolerate-unready-endpoints with
    # v1.Service.PublishNotReadyAddresses.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: kdc-tcp
    - port: {{ .Values.service.port }}
      protocol: UDP
      name: kdc-udp
  clusterIP: None
  selector:
    app: {{ template "hdfs-k8s.krb5.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hdfs-k8s.krb5.fullname" . }}-node-port
  labels:
    app: {{ template "hdfs-k8s.krb5.name" . }}
    chart: {{ template "hdfs-k8s.subchart" . }}
    release: {{ .Release.Name }}
  annotations:
    # TODO: Deprecated. Replace tolerate-unready-endpoints with
    # v1.Service.PublishNotReadyAddresses.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: kdc-tcp
      nodePort: 30226
    - port: {{ .Values.service.port }}
      protocol: UDP
      name: kdc-udp
      nodePort: 30226
    - port: 464
      protocol: TCP
      name: admin-tcp
      nodePort: 30227
    - port: 464
      protocol: UDP
      name: admin-udp
      nodePort: 30227
  selector:
    app: {{ template "hdfs-k8s.krb5.name" . }}
    release: {{ .Release.Name }}